export enum ErrorCode {
  NOT_FOUND = "NOT_FOUND",
  INVALID_PARAMS = "INVALID_PARAMS",
  TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
  DUPLICATED = "DUPLICATED",
  FAIL_CREATE_SALT = "FAIL_CREATE_SALT",
  FAIL_CREATE_PASSWORD = "FAIL_CREATE_PASSWORD",
}
